language: cpp
branches:
  only:
  - master
  - travis-deploy

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - BUILD_CONFIGURATION=Debug
    - VIRT86_COMPILER_NAME=GCC7

  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - BUILD_CONFIGURATION=Release
    - VIRT86_COMPILER_NAME=GCC7

  - os: osx
    osx_image: xcode10.1
    env:
    - BUILD_CONFIGURATION=Debug
    - VIRT86_COMPILER_NAME=LLVM

  - os: osx
    osx_image: xcode10.1
    env:
    - BUILD_CONFIGURATION=Release
    - VIRT86_COMPILER_NAME=LLVM

before_install:
- eval "${MATRIX_EVAL}"
- VIRT86_ARTIFACT_PATH="${TRAVIS_BUILD_DIR}/build/_artifact"

script:
- mkdir build
- cd build
- mkdir ${VIRT86_ARTIFACT_PATH}
- cp ${TRAVIS_BUILD_DIR}/README.md ${VIRT86_ARTIFACT_PATH}
- cp ${TRAVIS_BUILD_DIR}/LICENSE ${VIRT86_ARTIFACT_PATH}
- cmake .. -DCMAKE_BUILD_TYPE=${BUILD_CONFIGURATION} -DCMAKE_INSTALL_PREFIX=${VIRT86_ARTIFACT_PATH}
- make install
- |
  if [[ -z "${TRAVIS_TAG}" ]]; then
    VIRT86_VERSION=1.0.1-b${TRAVIS_BUILD_NUMBER};
  else
    VIRT86_VERSION=$(echo ${TRAVIS_TAG} | cut -c2-);
  fi
- VIRT86_PACKAGE_NAME=virt86-${VIRT86_VERSION}-${VIRT86_COMPILER_NAME}-x64-${BUILD_CONFIGURATION}.tar.gz
- tar -zcvf ${VIRT86_PACKAGE_NAME} ${VIRT86_ARTIFACT_PATH}
- echo Created package ${VIRT86_PACKAGE_NAME}
- cd ${TRAVIS_BUILD_DIR}

deploy:
  provider: bintray
  file: bintray.json
  user:
    secure: gb/4SCP6yLtsq7EV9eLQ55MNNWB358RiO9qYcaddRppYJEpBndy/FqwdYbeAJh6v2hzbKx48y1sGC49y50wmnTNMDi15+Sah+vJIgdvEavCf7j3dy1sylVzOFhQ0p5I3XYiijtxtHGqmnKZ3x9ftg/F8fIlzZVPcBeBosZoZjpcilvcXahYmNIUHBNjk2wuOtbyGW/ftS8Rl4nHeulSxEUrhRoi4L0Er7pi2pzFOut9cRP5eIKZAw8K8G9XgYYrr9m+b7zOmrYmikocHGCRqC1s1M5OxfJYBbo60Qba45lWuH4fXsZkhpsD7SETEWkrU31+mKv3qkb/aDnXkotFWoMvppQpNl/gfem5nHJP5QaE3n9SaGi1u9LG5Docf+yh65has6aYfV2PNL+aXwLuYxHBxkuN+rCKyaiIrJe4CeAxXLBXy3Y8tIrQ8CZdfkp48vDOl9IMJCq6ohFABhiDvdxT2CSUxh+EQu7sukygLDbPwW6JpM/PL0b1CuQcTZeuZUovEGm6TV+5Ec+UIzWdwcd2PZplnkZNgXNgL2C26xX2vjG36I9xRFAZm6Xltw/zmGzZGk8gqwI8NrruVfYeoyYzM+KBg1IGn049h54gaf5CeKx40CHJEaVXDej8l5Ef9hIRT9UJwGIiVcwAIfBXV0rSRcRd2pGd1YdHWvjJpA3k=
  key:
    secure: RrhEUD77O1jJ+pbtG24ymEs7T87H4+KoQ1gCpgUOU52dlcoOzZwkUMqPIFIpqFwmK4gwKof6yTFMrVQ0o3naUsHmEQzr+rTSs1v+Zgec2ygB37s0Wxwj+F6LIcawVDLNULH7h7a41yRqqlizXhfMJ75sF16rIkigF/l0/Nupx+Lr99EBp5RgJnqX93VmYJzq8rDpZ1ULfjIYIHCO5BIuLHPQz+aXps44u3ece2Lw8CnmQFXamncQtSFtuars9QOkdY3xlrY9Nay29G71rQgJw/jyfx+AV+ei657zUDKwvsBNJWy48B+XFdmkasvJ7ymz+WLEDYWseFOJMzA9OCCPaVFFUDCZXsWbBZSEGXIjdhuOjnSl8nA/JBd911VOpK1hT0L13B36kitguc1GzkZIitUcb8OJMo8RCCVa+h2pmW9yf4DHsnhE5LVSRJS74txWEPV1Vs5XMe/5G5pY6+GXedPQRk7Bw8IhLQaim9CG4pN7ZzXcwHiiEtMQrqpH8U0NOyhHy6d1TuPrjGb3eg5aXzmbiWHytF7Z8VJxa/8nS1PhHoAkpDZMJrMoNYPrkpkuVfC9R4t19cBMP+OnqDZsQQI+8fYE3Sj+bDRFYnn8lMON6bGofhXWvkb00DRJOl3zNM3B6sUeTdOO5sseLaCCmOiW7veF2eYBQlJzIXM+2E8=
  skip_cleanup: true
  dry_run: false
  on:
    all_branches: true
