language: cpp
branches:
  only:
  - master
  - travis-deploy

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - BUILD_CONFIGURATION=Debug
    - VIRT86_COMPILER_NAME=GCC7

  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - BUILD_CONFIGURATION=Release
    - VIRT86_COMPILER_NAME=GCC7

  - os: osx
    osx_image: xcode10.1
    env:
    - BUILD_CONFIGURATION=Debug
    - VIRT86_COMPILER_NAME=LLVM

  - os: osx
    osx_image: xcode10.1
    env:
    - BUILD_CONFIGURATION=Release
    - VIRT86_COMPILER_NAME=LLVM

before_install:
- eval "${MATRIX_EVAL}"
- VIRT86_ARTIFACT_PATH="${TRAVIS_BUILD_DIR}/build/_artifact"

script:
- mkdir build
- cd build
- mkdir ${VIRT86_ARTIFACT_PATH}
- cp ${TRAVIS_BUILD_DIR}/README.md ${VIRT86_ARTIFACT_PATH}
- cp ${TRAVIS_BUILD_DIR}/LICENSE ${VIRT86_ARTIFACT_PATH}
- cmake .. -DCMAKE_BUILD_TYPE=${BUILD_CONFIGURATION} -DCMAKE_INSTALL_PREFIX=${VIRT86_ARTIFACT_PATH}
- make install
- |
  if [[ -z "${TRAVIS_TAG}" ]]; then
    VIRT86_VERSION=1.0.1-b${TRAVIS_BUILD_NUMBER};
  else
    VIRT86_VERSION=$(echo ${TRAVIS_TAG} | cut -c2-);
  fi
- VIRT86_PACKAGE_NAME=virt86-${VIRT86_VERSION}-${VIRT86_COMPILER_NAME}-x64-${BUILD_CONFIGURATION}.tar.gz
- tar -zcvf ${VIRT86_PACKAGE_NAME} ${VIRT86_ARTIFACT_PATH}
- echo Created package ${VIRT86_PACKAGE_NAME}
- cd ${TRAVIS_BUILD_DIR}

deploy:
  provider: bintray
  file: bintray.json
  user: strikerx3
  key:
    secure: AIIkd0om56Hx/9olcHgN3P3OROhTm1Xa3prnq/PK0jX63gieT269OBQGZQC1SZhyDtuxODHfWPGeG8jJ4JhxcjJ7yc5KZh3AvrEkNs+F35gF0ZvN/98pSCkQP3coTbASoTzCzhHbIzecIZ4zd9ql0707UIc557vKvzQFP08+1TpuaSXnUnVX0Itw/tOHS56ejqu7jPtkWpAZSAI5lZWxPyAIRwYsoTVlXeoxjFZLgYV2pSRdKO8cvhdTcA5hYE3SMVwIfUuKOS3osuhUDZIvd3cbK/qch3w7ozLfvQ6x8eSu2bLG2wO2pI5ABFHqJ74WL9n8mPs2s4u4coN/CEeoNypaysk2Inr1beIIoxgZq0p9MRzxJD59VIKtuDE2krZofMww0zVl84BzCSKML7s+B0v3iWZbpmuRrJuk9vRwsZadzFBUSMh6WPrdXVm89oEzg8A64U3xLdp3KAZkk9vBDAoNuq0ufcOaIdCTWCVWDspJRCH8+Ud21FzqS9hDs+YB4CRObjKu4P9fwiBbKyrEgGZ98vrH3hRlrtEdHsz+wHtPngNPVDd4KKg2eaGlYW+AAam6lHOYZKpK/Z0wCMAiQHzXVg/yQea8bMKkkHmfpFzwV5NCfjN8+/r7GL23ZPFxT3N1vPMlIDFLstgLqg4ZW4qUEtmuAaaaTrHUt4C9e/Q=
  skip_cleanup: true
  dry_run: false
  on:
    all_branches: true
