language: cpp
dist: xenial
os: linux
compiler:
- gcc
- clang
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
branches:
  only:
  - master
  - travis-ci

before_install:
- eval "${MATRIX_EVAL}"

script:
- mkdir build
- cd build
- cmake .. && make
