language: cpp
# os: linux
# dist: xenial
# compiler: gcc
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode10.1
branches:
  only:
  - master
  - travis-mac

before_install:
- eval "${MATRIX_EVAL}"

script:
- mkdir build
- cd build
- cmake .. && make
